parameters:
services:
    kisiowall.caller.service:
        class: AppBundle\Services\KisioApiCaller
        arguments:
          - %twitter_key%
          - %twitter_secret%
    github.caller.service:
        class: AppBundle\Services\GithubApiCaller
        arguments:
          - %github_token%
    rooms.caller.service:
        class: AppBundle\Services\AvailableRoomsCaller