parameters:
services:
    kisiowall.caller.service:
        class: AppBundle\Services\KisioApiCaller
    github.caller.service:
        class: AppBundle\Services\GithubApiCaller
        arguments:
          - @memcache.default
    rooms.caller.service:
        class: AppBundle\Services\AvailableRoomsCaller